name: Print Message

on:
  push:
    branches: 
      - 'main'


jobs:
    print-message:
      runs-on: ubuntu latest

      steps:
          - name: Print Message
            run: echo "New push will be detected on main branch"
