Name: Pipeline With Stages
on:
  push:
    branches:
      - 'main'
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Build Project
            run: echo "Building th project"

    test:
      runs-on: ubuntu-latest
      needs: build
      steps: 
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Test Project
            run: echo "Testing the Project"

    deploy:
      runs-on: ubuntu-latest
      needs: Test
      steps: 
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Deploy Project
            run: echo "Deploy the project"